
#ifndef __KERNEL_IOCTLS_H__
#define __KERNEL_IOCTLS_H__

#include <ntifs.h>
#include "general-types.h"
#include "ioctls.h"



#define IOCTL_REMDISK_INTERNAL_START			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x01, METHOD_NEITHER, FILE_WRITE_ACCESS)
#define IOCTL_REMDISK_INTERNAL_QUERY			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x02, METHOD_NEITHER, FILE_READ_ACCESS)
#define IOCTL_REMDISK_INTERNAL_PASSWORD			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x05, METHOD_NEITHER, FILE_WRITE_ACCESS)
#define IOCTL_REMDISK_INTERNAL_SAVE				CTL_CODE(FILE_DEVICE_UNKNOWN, 0x06, METHOD_NEITHER, FILE_READ_ACCESS)
#define IOCTL_REMDISK_INTERNAL_LOAD				CTL_CODE(FILE_DEVICE_UNKNOWN, 0x07, METHOD_NEITHER, FILE_WRITE_ACCESS)
#define IOCTL_REMDISK_INTERNAL_WRITABLE			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x08, METHOD_NEITHER, FILE_WRITE_ACCESS)
#define IOCTL_REMBUS_PDO_GET_DISKINFO			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x9, METHOD_NEITHER, FILE_READ_ACCESS)





#endif
